# API Gateway - Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.ultrahpm: DEBUG
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
