# Product Service - Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.ultrahpm.product: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
