# User Service - Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.ultrahpm.user: DEBUG
    org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
